excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://erichilarysmithsr.github.io
name: Yellowscreen Software Blog
description: This is about new software update using GitHub integrations with Android and Chrome.
author: Eric Hilary Smith
avatar: http://www.gravatar.com/avatar/b280d6223bab517156c7aeee7b93d3b8?s=120&d=mm&r=g
ga_domain: 
ga_tracking_id: 